export * from './StatesQueries';
export * from './CourseQueres';
export * from './SchoolQueries';
export * from './UserQueries';
export * from './RolQueries';
export * from './LanguajeQueries';
export * from './TopicQueries';
export * from './ModuleQueries';
export * from './TypeCourseQueres';