export * from './ApiResponse';
export * from './IRol';
export * from './ISchool';
export * from './ICity';
export * from './IStates';
export * from './ICourse';
export * from './IUser';
export * from './ILanguaje';
export * from './ITopic';